brailcom/speechd

- INSTALL
> document that gettext is needed to regenerate configure too

- configure.ac
We shouldn't be requiring kali.
> Fix default value of --with-kali

- src/api/python/speechd_config/config.py.in
> spd-conf: complete list of supported syntheses

- src/audio/pulse.c
- src/modules/module_utils.c
- src/modules/module_utils.h
so it shows up in pavucontrol etc.
> pulse: Pass module name as stream name

- config/modules/espeak-mbrola-generic.conf
- config/modules/espeak-ng-mbrola-generic.conf
More mbrola voices have been ported to espeak, so update voice list.
And fix some ISO incoherences.
> espeak-*-mbrola-generic: update voice list

- src/modules/module_utils_addvoice.c
I didn't test that thoroughly but it should fix the leaks and misallocations from b08a26c881f32be3b85d6dfeaf8cb0eb55a6f79b (#50)
> Fix a few leaks and allocation issues from last commit

- config/modules/espeak-ng-mbrola-generic.conf
to match the current handling of the mbrola voices by espeak-ng.
> espeak-ng-mbrola-generic: update the voice list

- configure.ac
- src/modules/Makefile.am
- src/modules/baratinoo_shim.c
to be able to build the Baratinoo module without the Baratinoo SDK.
> baratinoo: Add a shim

- configure.ac
- src/modules/Makefile.am
- src/modules/kali.cpp
- src/modules/kali_KAnalyse_shim.cpp
- src/modules/kali_KGlobal_shim.cpp
- src/modules/kali_KParle_shim.cpp
- src/modules/kali_KTrans_shim.cpp
- src/modules/kali_Kali_shim.cpp
- src/modules/kali_shim/kali/Kali/kali.h
to be able to build the Kali module without the Kali SDK.
> kali: Add a shim

- config/speechd.conf
espeak is not maintained any more.
> Change default module to espeak-ng

- README.overview.md
Espeak NG, Kali, Baratinoo (Voxygen)
> Add newly added synthesis in README.overview.md

- src/clients/say/say.c
> spd-say: set default language to the current locale

- src/modules/espeak-ng.c
- src/modules/espeak.c
- src/modules/festival_client.h
- src/modules/module_utils.h
- src/server/speechd.h
Thanks Colomban Wendling for the suggestion
> Fix safety of macro calls

- src/modules/baratinoo.c
This also works around the issue with misdetection of mark order in `module_tts_output_marks()` which #170 fixes.
Part of #169.
> baratinoo: Simplify recording marks sample offset

- config/modules/dtk-generic.conf
- config/modules/epos-generic.conf
- config/modules/espeak-generic.conf
- config/modules/espeak-mbrola-generic.conf
- config/modules/espeak-ng-mbrola-generic.conf
- config/modules/llia_phon-generic.conf
- config/modules/mary-generic.conf
- config/modules/pico-generic.conf
- config/modules/swift-generic.conf
- src/server/module.c
To avoid cluttering the list of available modules with useless entries.
> generic modules: check for actual availability of binaries

- config/modules/espeak-ng.conf
- config/modules/espeak.conf
- src/modules/espeak-ng.c
- src/modules/espeak.c
to be able to disable indexing in espeak and espeak-ng
> Add EspeakIndexing option

- src/modules/espeak.c
Same as 4fdec88e027e08fa797122f80ad6581b5d8afb79, but for espeak
> Fix atomicity of accessing espeak_close_requested with conditions

- src/modules/Makefile.am
- src/modules/espeak-ng.c
- src/modules/espeak.c
- src/modules/module_utils_speak_queue.c
- src/modules/module_utils_speak_queue.h
So it can be used by other modules too.
> Move audio queueing from espeak/espeak-ng to shared file

- src/modules/module_utils_speak_queue.c
> Rename symbols to general names

- src/server/symbols.c
SSML is not only composed of "'<>&, but also / and whatever shows up in mark
names, so it's not actually reasonable to make the regexps use entities.
Instead we can mask out SSML tags by using U+E0XY and replace entities
with normal text, so that the unmodified regexps can work.
> symbols: Fix SSML support

- src/server/symbols.c
This will be useful for font variant replacement support for #217.
> symbols: Add literal replacement option

- src/server/symbols.c
> Fix dropping U+Exxx characters

- speech-dispatcher.pc.in
> Relicence speech-dispatcher.pc.in to LGPL

- src/modules/baratinoo.c
Add ABI compatibility for VoxyGen's Baratinoo 8.6.
Changes in upstream ABI since 8.4 are:
* `BCinputTextBuffer()` got a new last `uri` argument.
It otherwise is compatible with 8.4 ABI.
> baratinoo: Add support for Baratinoo engine 8.6

- locale/README.md
- locale/en/font-variants.dic
* unicode-data.txt was not updated durring last symbols update, it is now at the last version from unicode.org
* Fix bad formed link for unicode-data.txt in locale/README.md
> Update unicode font variants and fix locale READme file

- config/speechd.conf
- src/server/symbols.c
emojis + gender neutral processing seems to be already too big for PCRE.
We can however process them one after the other instead of everything
altogether. This will actually be simpler for people that files are
processed one by one, without mixing symbols etc.
> Separate symbols processing in several passes

- src/server/symbols.c
-]^ have special meaning inside [], which g_regex_escape_string won't
escape, so escape by hand.
> symbols: Fix including -]^ in simple symbols

- src/server/symbols.c
U+E0xy make obstacle to rules matching ^ and $.  A simple solution is to
just take them away while parsing.
> symbols: fix maching ^ and $ with ssml

- src/server/symbols.c
U+E0xy characters get in the way of lookbehind and lookahead rules.
Instead of using them, really remove the tags, remembering where they
were, and shifting that when performing replacements.
> symbols: Improve SSML management

- src/api/python/speechd/client.py
- src/server/parse.c
> Add support for getting the current punctuation level

- src/modules/baratinoo.c
- src/modules/cicero.c
- src/modules/espeak-ng.c
- src/modules/espeak.c
- src/modules/festival.c
- src/modules/flite.c
- src/modules/generic.c
- src/modules/ibmtts.c
- src/modules/ivona.c
- src/modules/pico.c
And document where modules could get generic better support for
SPELL/CHAR/KEY.
> Fix KEY command for baratinoo

- src/server/parse.c
> server: Make key, char and sound_icon commands return message id

- configure.ac
as now allowed by FHS 3.0
Fixes #360
> Move speech dispatcher modules to /usr/libexec

- po/fr.po
Currently translated at 100.0% (164 of 164 strings)
Translation: speech dispatcher/po
Translate-URL: https://hosted.weblate.org/projects/speech-dispatcher/po/fr/
> Translated using Weblate (French)

- po/LINGUAS
Since Russian and French have been added recently, these languages was not listed in po/LINGUAS
> Add missing languages

- src/api/python/speechd/client.py
> Make the Python API close automatically

- src/modules/ibmtts.c
which is reported upcase by ibmtts at least.
> ibmtts voxin: Fix matching country

- src/modules/ibmtts.c
Since we pass pieces of text separated by marks, ibmtts would speak
<speak> and </speak> when they are alone in their pieces.
> ibmtts voxin: Drop <speak> and </speak>

- src/modules/ibmtts.c
The semaphore is far enough to get the synth thread to terminate.
> ibmtts voxin: Clean module termination

- config/speechd.conf
Thanks Inglebard for the proofreading.
> Fix documentation order

- doc/speech-dispatcher.texi
> Mention the golang interface also in the texi doc

- po/nb_NO.po
Currently translated at 70.7% (116 of 164 strings)
Translation: speech dispatcher/po
Translate-URL: https://hosted.weblate.org/projects/speech-dispatcher/po/nb_NO/
> Translated using Weblate (Norwegian Bokmål)

- doc/speech-dispatcher.texi
- src/api/c/libspeechd.c
- src/api/python/speechd/client.py
This allows users to define the speechd server to auto-spawn.
Fixes #463
> Add SPEECHD_CMD environment variable

- doc/speech-dispatcher.texi
- src/modules/Makefile.am
- src/modules/module_config.c
- src/modules/module_main.c
- src/modules/module_main.h
- src/modules/module_process.c
- src/modules/module_readline.c
- src/modules/module_utils.c
- src/modules/module_utils.h
- src/modules/skeleton0.c
- src/modules/skeleton0_espeak-ng0.c
- src/modules/skeleton0_espeak-ng1.c
- src/modules/skeleton_config.c
This will allow proprietary modules to easily reuse this as a basis.
> modules: Rewrite main functions with BSD licence

- TODO
- doc/speech-dispatcher.texi
- src/modules/module_main.h
- src/modules/module_process.c
- src/server/module.h
- src/server/output.c
This is for now quite synchronous, we still need to move the playback to its
own thread, like the espeak audio queue.
> Support playing audio through server

- src/modules/module_process.c
- src/server/output.c
Rather than getting a long series of lines, which entail more protocol
management.
> Transfer audio with HDLC escaping

- src/server/output.c
The module structure is not zeroed
> Fix crash using module-side audio output

- src/modules/flite.c
- src/modules/module_main.h
- src/modules/module_process.c
- src/modules/skeleton0.c
- src/modules/skeleton0_espeak-ng0.c
- src/modules/skeleton_config.c
> flite: Vastly simplify the module

- src/api/guile/gssip.h
- src/clients/say/options.h
- src/clients/spdsend/spdsend.h
- src/modules/festival_client.h
- src/modules/module_utils.h
- src/server/configuration.h
- src/server/history.h
- src/server/output.h
- src/server/speaking.h
Otherwise C compilers do not actually check parameters.
> Add void parameters

- src/modules/module_process.c
According to what we had before the rewrite
> module_process: Fix parameter codes

- src/modules/espeak.c
This saves using threads and all very complex synchronization questions.
> espeak/espeak-ng: Run in synchronous mode

- src/modules/kali.cpp
> Fix kali's module_speak prototype

- src/modules/kali.cpp
We need an addition cell for the trailing NULL.
> kali: Fix voices array size

- src/modules/module_process.c
We do not want to take the time to send megabytes of data at a time, we
would not stop in between. The synth might still be giving up this, so
split ourself in chunks of reasonable size, and also manage stopping
early.
Fixes #542
> module_process: Fix reactivity for long messages

- src/modules/generic.c
The server was previously still waiting for it to complete.
Fixes #549.
> generic: Fix sound icon play

- src/modules/festival.c
It otherwise has a long latency.
> festival: strip head silence

- src/modules/ivona_client.c
We do not want to list the ivona voice if the server is not available.
> ivona: probe for server at startup

- src/modules/ibmtts.c
We do not need to update the bytes actually.
> ibmtts: Fix warning

- configure.ac
- src/server/Makefile.am
- src/server/speechd.c
> module: Restore loading from lib/speech-dispatcher-modules

- src/modules/Makefile.am
> modules: Drop gthread

- configure.ac
Binaries are available only for that case.
> IBMTTS: Do not build by default on other systems that 32bit PC

- src/modules/module_main.c
do_quit already calls it
This fixes double-frees
> Do not call module_close on normal termination

- doc/speech-dispatcher.texi
- src/common/spd_audio.c
This allows to run by hand new audio modules.
> Add SPEECHD_PLUGIN_DIR environment variable

- src/modules/flite.c
So the voice list is not empty.
> Make flite module at least return one voice

- po/hu.po
Dear Samuel,
I updated the Speech Dispatcher hungarian translation, now all translatable messages are localized perfectly.
If you have a little time, please merge this pull request into upstream Speech-dispatcher master branch before the new release publication.
Take care, and have you a nice day,
Attila Hammer
> Update hungarian translation

- src/server/symbols.c
> symbols: Turn xx-yy locale designation with xx_YY

- src/tests/.gitignore
- src/tests/Makefile.am
- src/tests/clibrary2.c
And instead introduce clibrary3 that does it.
> clibrary2: avoid iterating over each and every voice

- src/api/c/libspeechd.c
- src/api/c/libspeechd.h
For cleaning up the result of spd_list_voices.
> Add free_spd_symbolic_voices

- .github/workflows/ci.yml
> Enable clibrary2 in CI

- NEWS
- README.overview.md
- doc/speech-dispatcher.texi
- doc/ssip.texi
- src/api/c/libspeechd.c
- src/api/c/libspeechd.h
- src/api/python/speechd/client.py
- src/api/python/speechd_config/config.py
- src/audio/alsa.c
- src/audio/nas.c
- src/audio/oss.c
- src/common/spd_audio.c
- src/modules/dummy.c
- src/modules/generic.c
- src/modules/module_main.h
- src/server/output.c
- src/server/parse.c
- src/server/server.c
- src/server/speaking.c
- src/server/speechd.c
- src/tests/README
- src/tests/clibrary.c
- src/tests/clibrary2.c
- src/tests/connection-recovery.c
- src/tests/spd_cancel_long_message.c
Found via `codespell -q 3 -S *.po`
> Fix various typos

- src/audio/nas.c
- src/audio/oss.c
> Fix source typos

- src/modules/module_main.h
ditto. I don't understand how this has worked before?
> Add missing pthread include

- configure.ac
- doc/Makefile.am
> Only generate html documentation on the maintainer system

- .github/workflows/ci.yml
- .github/workflows/testsuite.yml
- Makefile.am
- configure.ac
- speech-dispatcher.service.in
- speech-dispatcher.socket
- src/server/Makefile.am
- src/server/speechd.c
Fixes  #336.
I followed Jhenstridge's guidelines therein, and though `spd-say` still works, I wonder if the Systemd socket activation (which is the whole point) is working; I'll be happy to follow instructions to test it in regards to that.
> Implement socket activation

- config/speechd.conf
> Fix spd-conf not being able to set the default module

- speech-dispatcher.service.in
We need to prevent speechd from forking to daemon, otherwise systemd thinks it stopped.
Fixes #809
> Fix Service activation via socket

- src/api/c/libspeechd.c
spd_execute_command_with_list_reply was accidentally quadratic: it would start by searching the string for one \r\n, then it would search for two, then for three...  I have 15,000 voices (I have no idea why; it seems to be the default Debian config), so this was quite slow.
For me, this improves the performance of spd_list_synthesis_voices from 1.5s to 0.5s.
> Speed up spd_execute_command_with_list_reply

- doc/speech-dispatcher-cs.html
- doc/speech-dispatcher.html
- doc/speech-dispatcher.texi
- doc/ssip.html
- doc/ssip.texi
- src/api/c/libspeechd.c
- src/api/c/libspeechd.h
- src/api/python/speechd/_test.py
- src/api/python/speechd/client.py
- src/clients/say/say.c
- src/modules/module_process.c
- src/server/module.c
- src/server/output.c
- src/server/output.h
- src/server/parse.c
> Add language and variant parameters to "list voice" command

- src/audio/alsa.c
- src/audio/libao.c
- src/audio/nas.c
- src/audio/oss.c
- src/audio/pulse.c
which are not supported on MacOS
Fixes #851
> Avoid using gcc aliases

- src/clients/say/say.c
- src/modules/cicero.c
- src/modules/dummy.c
- src/modules/generic.c
- src/tests/clibrary2.c
> Use named semaphores for macOS compatibility

- src/modules/generic.c
Otherwise if the speech command fails, the user just hopelessly gets no speech any more, without speech-dispatcher falling back on something that works.
> generic: Abort when speech failed

- src/server/output.c
The event-consuming thread would get stuck in pthread_cond_wait on unexpected output if the main core thread is not actually waiting for anything.
> core: Protect against unexpected output from module

- src/server/speechd.c
through the SPEECHD_SOCK_FD environment variable.
> Allow to specify the listening socket fd

- NEWS
- README.md
- doc/speech-dispatcher.html
- doc/speech-dispatcher.texi
- src/modules/.gitignore
- src/modules/Makefile.am
for making it simpler to create external spd modules.
Fixes #918
> Add libspeechd-module library

- src/modules/module_utils.c
This indentation looks clearer to me.
> Fix indentation

- src/modules/espeak.c
See https://github.com/espeak-ng/espeak-ng/issues/2028
Fixes #949
> espeak-ng: Ignore samplerate change when it is not first in the event list

- src/clients/spdsend/client.c
- src/clients/spdsend/server.c
- src/clients/spdsend/spdsend.h
- src/server/history.c
> Fix build with -std=gnu23

- INSTALL
build.sh does much more than just autoreconf
> INSTALL: Fix autoreconf documentation

- src/modules/generic.c
dash does support set -o pipefail
> Use /bin/sh instead of requiring bash

- src/server/symbols.c
So people do not care too much about the failures.
> symbols: Also report successes
