src/modules/kali.cpp

So they are normalized at the default values being 0.

Fix Kali rate, volume, and pitch computations

---

src/api/c/libspeechd.c
src/clients/spdsend/spdsend.c
src/common/spd_getline.c

The getc() function returns an int.  A char variable cannot hold
all possible return values, in particular EOF.  In practice, with
EOF==-1, this idiom
while ((ch = getc(f)) != EOF)
will fail in two ways:
* On platforms where char is an unsigned type by default (ARM, PowerPC),
the loop condition will never be false.
* On platforms where char is signed, the loop will prematurely exit
when a char -1 (0xFF) is read.

Fix getc() usage

---

config/modules/baratinoo.conf
src/modules/baratinoo.c

speech-dispatcher might send to Baratinoo some punctuation characters
that it hopes will be taken for intonation, but Baratinoo would actually
pronounce, so we need a list of such characters to avoid the
pronunciation when punctuation level is none.

baratinoo: support blacklisting some punctuation characters

---

src/audio/pulse.c
src/modules/dummy.c

So it shows up as speech-dispatcher in pavucontrol like other speech modules
instead of "paplay".

pulse: Set pulse client name when using paplay

---

src/audio/pulse.c

so that volume is recorded by pulseaudio per module name, instead of
confusingly mixing volumes of the different modules.

pulse: Put module name into client name

---

src/audio/pulse.c

By using the speech-dispatcher-generic client name in the play command.

pulse: Make generic modules use the generic volume level

---

config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf

That was a leftover from the copy/paste from the espeak configuration.

espeak-*mbrola-generic: do not mentioned using espeak-generic

---

doc/speech-dispatcher.texi
src/server/module.c
src/server/module.h
src/server/speechd.c

So that all something-generic output modules are available without
having to modify the main configuration file.
Fixes #41.

Detect generic configuration files

---

configure.ac
src/api/c/libspeechd.c
src/clients/spdsend/server.c
src/clients/spdsend/spdsend.c
src/server/output.c
src/server/speechd.c
src/tests/run_test.c

Years ago, Willie Walker contributed fixes for building on Solaris 10 using #ifdef checks for the Solaris compilers and GNU libc.
This pull request converts these to autoconf checks so that you can build on Solaris with either gcc or Solaris compilers, and so that when building on current Solaris releases you don't redefine functions that Solaris 10 did not have but Solaris 11 now does.  (It should also improve portability to other non-Linux systems.)
The -lsocket -lnsl checks could be simplified by using AC_SEARCH_LIBS, as is done in https://gitlab.freedesktop.org/xorg/lib/libxtrans/blob/master/xtrans.m4#L28-30 - but then the results would just be in $LIBS, not split out into $EXTRA_SOCKET_LIBS as was done before, so
I didn't do that.

Convert old #ifdefs for Solaris into autoconf checks

---

config/modules/espeak-ng-mbrola-generic.conf

which just lets espeak-ng output audio.
Its advantage is to be audio output agnostic, which helps e.g. when using
libao as libao.c does not set PLAY_COMMAND (as it can speak to other audio
apps).
This is not the default, though, as this prevents to set the sound
volume from the client. Which is not that useful IMHO, but I can be
wrong.

espeak-ng-mbrola-generic: propose alternative command line

---

src/modules/generic.c
src/modules/module_utils.h
src/modules/module_utils_addvoice.c

Allow to actually set the chosen voice, for instance typing "spd-say -y
<voice>" or using the Voices->Person drop down list of Orca Preferences.

generic: Allow actually setting the synthesis voice

---

config/speechd.conf
src/audio/pulse.c

speech-dispatcher requests a total latency of 1 ms, which in turn gives
sub-ms latency inside the PulseAudio engine. This causes unnecessary CPU
consumption, or underruns. I understand that you would want immediate
feedback, but 20 ms seems more reasonable.
Fixes #45

speech-dispatcher defaults to extreme low latency

---

src/modules/baratinoo.c

Add translation from SSML to Baratinoo's proprietary format for the `<say-as>` tag.  It's pretty similar, and the same set of attributes are supported.

baratinoo: Add support for SSML say-as tag

---

Makefile.am

It is needed to be able to build from scratch.

Do not remove po/Makevars

---

src/modules/module_utils.h

str may be NULL when the syntax is bogus in the configuration file. In
that case, better keep the default parameter than setting the option to
NULL, which may yield to segfaults in modules rather than simply the
default behavior.

Fix taking into account bogus configuration lines

---

src/modules/Makefile.am

which is needed on some archs when the compiler does not enable PIE by
default.

Build module shims with -fPIC

---

src/server/output.c

It can not be NULL and is already dereferenced above anyway

Drop useless test for atoms pointer

---

src/modules/module_utils.c

Fix detecting the marks order, and properly report all marks.
Part of #169.

module_tts_output_marks() fixes

---

src/modules/module_utils.c

This allows modules to still use the audio output in module_close().
This is especially important if module_stop() doesn't actually stop the playback but simply posts a stop request (which the Pulse output make awfully easy), as it allows the module to rely on the output honoring the request for normal operation, and only perform careful cleanup (including shutting down any audio remains) in module_close().
This actually fixes an intermittent crash in at least the Baratinoo module, but other modules are likely affected.
Closes #169.

Close the audio output after closing the module

---

config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/mary-generic.conf
config/modules/pico-generic.conf

They do not pose problem any more thanks to 808b9fb27484 ('Fix taking
into account bogus configuration lines').
Thanks Didier Spaier <didier@slint.fr> for spotting them!

Remove spurious space in string configurations

---

src/api/python/speechd_config/config.py.in
src/clients/say/options.c
src/server/options.c

which notably fixes them in manpages.

Make copyright notices coherent in --help and --version

---

src/server/parse.c

They are not useful for end users.

module list: exclude dummy and generic

---

src/modules/baratinoo.c

module_tts_output produces audio glitches which are more disturbing than
marking is useful for now.

baratinoo: disable marking for now

---

src/modules/generic.c

--punct-none/some/all is not used by any known synthesis, and dotconf's
parsing doesn't allow using
GenericPunctNone ""
to actually erase a non-empty default.

Set default GenericPunctNone/Some/All to empty

---

src/modules/generic.c

Declare GenericCmdDependency option

---

src/api/guile/gssip.h
src/clients/spdsend/spdsend.h
src/tests/spd_cancel_long_message.c
src/tests/spd_set_notifications_all.c

This helps resolve possible incompatibility with software licensed
under later (L)GPL versions.
Approved by Mr Jan Buchal, director of [BRAILCOM,o.p.s.](https://brailcom.org)

Add option to choose a later version of (L)GPL

---

configure.ac

We will needed it to generate speechd.desktop

Fail configure if we do not have msgfmt

---

src/modules/module_utils_addvoice.c

We shouldn't record voice names of voices which fail the dependency
path, and when choosing a voice, we should not only default on male1,
but anything else that might fit
Fixes #99

generic: fallback to existing voices

---

src/modules/espeak-ng.c
src/modules/espeak.c
src/modules/module_utils_speak_queue.c
src/modules/module_utils_speak_queue.h

We can simply make module_speak_queue_add_audio take an AudioTrack and
AudioFormat to avoid hardcoding anything in module_utils_speak_queue.

speak-queue: generalize audio parameters

---

src/audio/alsa.c

It seems that notably with virtual machines periods are not so stable,
so better have two periods ahead.

alsa: increase overlapping to two periods

---

src/server/symbols.c

When g_hash_table_insert replaces an existing entry, it keeps the
existing key, it does not replace it with the key of the new entry. We
thus must separate out freeing the entry and freeing the key.

symbols: fix multiple definitions

---

locale/import-symbols.py

I tried to update CLDR dictionaries to version 36 which has the most added new emojis.
During the process, I encounter errors with en_GB language:
* The derived annotations file doesn't exist
* The existing one doesn't provide TTS descriptions.
So I propose to update the symbols importation script to:
* Check if all CLDR files for a language exist before processing them
* Manage the assertion error if a XML file has no processable emojis
I successfully tried to generate dictionaries with this updated script, so after that we should be able to provide version 36 for CLDR characters.

Update symbols importation to be ready for update to CLDR 36

---

locale/Makefile.am
locale/README.md

The "symbolsrc" directory should be ignored by git as it is added manually when importing symbols and emojis dictionaries. I propose to add the directory to the GITIGNOREFILES variable in locale/Makefile.am.
I also noticed I forgot to add new emojis dictionaries to this make file in the PR importing last updated dictionaries.
To prevent avoiding this happening in the future, I suggest to add some precision about what to do when new dictionaries are imported when following instructions in locale/README.md

Improve locale make and add documentation for newly added dictionaries

---

locale/Makefile.am

When using DESTDIR Latin American Spanish languages emojis dictionaries point to the build root so making packages make broken links for these languages.
Fixes #271

Use relative path when creating symbolic links for Latin American Spanish  emojis

---

configure.ac

Fix typo in ibmtts shim check leading to shell warning:
> ./configure: line 17032: test: too many arguments

configure: Fix typo

---

NEWS
config/modules/Makefile.am
config/modules/mary-generic-disabled.conf

Otherwise it always prevents the dummy module from getting triggered to tell
the user that speech-dispatcher is working but no module is installed.

Disable Mary-TTS module by default

---

NEWS
config/speechd.conf
src/audio/pulse.c
src/modules/module_utils.c
src/server/alloc.c
src/server/configuration.c
src/server/output.c
src/server/server.c
src/server/set.c
src/server/speechd.h

Changing the pulse server is rarely useful for a user, while changing
the device definitely is. Let's keep the code for the server
configuration for now, enabling it will "just" need to break the module
parameter interface.

Replace AudioPulseServer option with AudioPulseDevice

---

src/modules/pico.c

By default pico would return just 2ms audio, it's a battery waste to push
only that tiny amount to audio stacks. Call pico several times to try to
get 50ms audio, but not more than 100ms so that interrupts remain
snappy.

pico: play at least 50ms at a time

---

locale/fr/gender-neutral.dic

glib doesn't support lookbehind with non-constant size.

Fix regexp not supported by glib

---

config/speechd.conf
src/server/configuration.c
src/server/symbols.c
src/server/symbols.h

We need to distinguish between symbol preprocessing that manages
character description (and thus should disable the module character
description processing) from other symbol preprocessing that shouldn't
disable character description processing.

Add CharSymbolPreprocFile directive

---

src/server/symbols.c

We need to gather the heading/trailing U+E0xy before unescaping, of
course.

symbols: Fix unescaping ssml U+E0xy

---

src/server/symbols.c
src/server/symbols.h

Otherwise we cannot choose it in the configuration file since -1 is
hardcoded to be for errors.

symbols: Separate out "no" from invalid

---

src/modules/Makefile.am

libibmeci.so is usually installed there, so make sure we automatically
try to get it from there.

ibmtts: Add runpath to /opt/IBM/ibmtts/lib

---

config/modules/dtk-generic.conf
config/modules/espeak-generic.conf
config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/llia_phon-generic.conf
config/modules/mary-generic-disabled.conf
config/modules/swift-generic.conf

printf %s '$DATA' allows to be sure none of $DATA is interpreted. Echo
does not provide this (e.g. DATA=-n).

generic: Use printf instead of echo

---

doc/ssip.texi
src/server/parse.c

Don't allow getting the client list.
Also don't allow getting message list for any client id
other than the current connection's client id.
Updated ssip.texi also.

Plug history security hole on the ssip side.

---

src/clients/say/say.c

spd_sayf interprets the string as a printf format, so we need to use %s
instead.

spd-say: Fix synthesizing percent

---

src/audio/pulse.c

When the sample format changes and we try to reopen our pulseaudio
connection, check for errors or else we end up passing a NULL to
pw_simple_write() and cause an abort.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1770778

pulse: handle _pulse_open() errors in reconnect

---

doc/speech-dispatcher.html
doc/speech-dispatcher.texi

spd_sayf interprets the string as a printf format, so we need to use %s
instead.

doc: Fix synthesizing percent

---

src/modules/ibmtts.c

This harmonizes the codestyle with the voxin module source:
- use gboolean/FALSE/TRUE
- drop ibtts_ prefixes
- Use DBG_MODNAME
- move update_sample_rate code.
- add DBG(DBG_MODNAME "ENTER %s", __func__);

ibmtts: harmonize with voxin module source

---

src/modules/ibmtts.c

So we can ask for 'fr' and get the first French language, with France
accent.

ibmtts: Add approximate language matching

---

doc/Makefile.am

We want to have .html files ready for read in the public web repository.
Fixes #394

doc/: Avoid cleaning html files

---

src/api/python/speechd/client.py

Thread.isAlive() was removed in python 3.9. Thread.is_alive() has been
available since python 2.6, so let's use that.
Fixes #402

Fix crash with python 3.9

---

configure.ac

Even if the libraries are actually available on the system.

Respect configure request for building the shim

---

src/modules/ibmtts.c

When SSML is disabled we turned SSML into raw text. We shall not process
it again, in case the client actually want to speak e.g. "<speak>".

ibmtts voxin: Fix speaking when SSML is disabled

---

src/modules/ibmtts.c
src/modules/voxin.h

Hi,
This patch has been checked with Voxin 3.2 (which may now insert sound icons/clicks) and speech-dispatcher 0.10.1 (voxin 3.2 includes a backport of this ibmtts voxin module).

voxin: set capitalization style (from cap_let_recogn)

---

src/modules/module_utils.c
src/server/output.c

SSIP uses the same dot stuffing as SMTP: any dot leading a line is to be
duplicated. Otherwise we would not be able to provide the ".." text to
the module, since it would be taken as ".".

Fix dot stuffing between core and modules

---

locale/Makefile.am

Emojis were not working at all following to the last CLDR database update, some new added languages were not correctly listed.
Known issue: it looks like a lot of punctuations symbols were added to the CLDR database and symbols.dic looks like replaced by emojis rules.
So a lot of punctuations which should not be spoken are now pronounced.

Fix missing backslashes in locale/Makefile.am

---

config/modules/dtk-generic.conf
config/modules/epos-generic.conf
config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/llia_phon-generic.conf
config/modules/mary-generic.conf
config/modules/swift-generic.conf
doc/speech-dispatcher.texi
src/modules/generic.c
src/modules/module_utils.h
src/modules/module_utils_addvoice.c

We should avoid remaining silent even if the client does not even tell which
language should be spoken. Adding the DefaultVoice lets generic modules have
a default voice choice.

Add DefaultVoice option for the generic module

---

src/modules/kali.cpp
src/modules/module_utils.h
src/modules/spd_audio.h

glib.h now includes <type_traits> when building as C++. But kali.cpp
includes it (via module_utils.h) inside an extern "C" block. This is
illegal.
Best practice is to use extern "C" in project header files, not around
include statements. So let's do that. module_utils.h already includes
glib.h, so we can use G_BEGIN_DECLS/G_END_DECLS there. spd_audio.h does
not, so I decided to write out the usual boilerplate, as including all
of glib.h just for G_BEGIN_DECLS/G_END_DECLS seemed like overkill.
Finally, I'll move config.h at the very top of kali.cpp, since I'm
touching this code anyway and that is the usual place to put it.
This is the minimum viable change required for speech-dispatcher to
build with glib master. As long as speech-dispatcher is combining C and
C++, it would be advisible to …

Fix build after glib e38982df

---

src/modules/module_process.c
src/modules/skeleton0.c
src/modules/skeleton0_espeak-ng0.c
src/modules/skeleton_config.c

This allows modules to properly handle pause/stop with synchronized API.

Make module_speak_sync have to call module_report_event_begin/end

---

src/server/output.c

We cannot afford getting canceled while we hold the mutex, the main
thread wouldn't be able to reaquire it...

Fix mutex hang on speak thread cancellation

---

src/modules/module_process.c
src/server/output.c

The module protocol usually embeds data in the multi-line continuations,
not on the termination line.

Audio transfer: restore 705 AUDIO multi-line termination

---

src/server/output.c

We disable asynchronous canceling while holding the output mutex to avoid
deadlocks, but we want to be cancellable inside the audio rendering.

server: Avoid getting stuck inside audio code

---

src/common/Makefile.am
src/common/common.c
src/common/common.h
src/common/speak_queue.c
src/common/speak_queue.h
src/modules/Makefile.am
src/modules/baratinoo.c
src/modules/espeak.c
src/modules/ibmtts.c
src/modules/module_utils.c
src/modules/module_utils.h
src/server/configuration.c
src/server/output.c
src/server/speaking.c
src/server/speechd.c
src/server/speechd.h

This will allow to reuse it for server-side audio rendering.
For now the server behavior is not changed, the code is just moved and
corresponding compilation details are fixed.

Move the speak queue to libcommon

---

src/common/speak_queue.c
src/common/speak_queue.h
src/server/output.c

We want to unlock all waiting threads as quickly as possible.

server: Fix flushing audio and pipe on long text

---

src/server/module.c
src/server/module.h
src/server/output.c
src/server/speaking.c

The main speaking loop needs an fd to know that we have audio events pending
to be read.

server: Fix missing wake-up

---

src/server/configuration.c

Defaults in modules is usually 1-10 seconds. Here we do not know the
encoding rate, ideally we should turn the parameter to milliseconds, but we
can do that after dropping the use of espeak_queue from modules, by then
changing the meaning in there.

Increase maximum queue size

---

src/server/module.h
src/server/output.c

We cannot open audio when starting modules, since that is before forking to
daemonize, and fork would drop the pulseaudio mainloop threads, and later on
pulseaudio would try to join etc. them, leading to mayhem.
So delay server-side audio initialization to when we actually need it.

server: Fix opening server-side audio with daemon mode

---

src/modules/module_process.c

module_speak may let BEGIN events start appearing before module_speak
returns, so we need to keep the stdout mutex locked to make them wait
for our OK SPEAKING answer.

module_process: avoid BEGIN events before OK SPEAKING

---

src/modules/flite.c
src/modules/module_utils.c
src/modules/module_utils.h

module_strip_silence was stripping silence also at sentence periods,
making it confusing. Separating it into module_strip_head/tail_silence
allows to strip at message very beginning or end only.

flite: Restore stripping silence

---

src/modules/Makefile.am

flite: Do not include audio source

---

config/speechd.conf

emojis.dic contains quite invasive rules, better process the more
fine-grain symbols.dic before this.
Fixes #529

symbols: process symbols.dic before emojis.dic

---

config/speechd.conf

As announced for 0.10, we planned to enable this so that synthesizers
have a coherent behavior.

symbols: Enable speechd symbols processing by default

---

src/modules/kali.cpp

There does not seem to be really any bound in kali... So better allocate
the arrays in global variables, hoping that overflows won't cause too
much trouble.
Also use much larger buffers, to lower the risks of triggering an issue.

kali: Strengthen getting voice/language

---

src/modules/espeak.c

espeak: Add missing input processing while pushing audio

---

src/server/speaking.c

With module-side audio there is no point in polling on the speak queue
With server-side audio, we should not poll for module output since that
is the module output processing thread that consumes it. We would
spuriously wake and try to read from an empty speak queue and block.

server: poll only on the module output or speak queue

---

src/common/speak_queue.h
src/server/output.c
src/server/output.h
src/server/speaking.c

There has always been a race between a client making a request from an
output module (e.g. voice list) while speaking is ongoing. Using select
on the underlying fd of a FILE* is also very doubtful.
We can "simplify" this by just starting a thread that processes the
events. We still have concurrency between client requests and speaking
requests, but this can be managed by dispatching replies and events
accordingly.
Fixes #541

server: rationalize processing events from output modules

---

src/modules/kali.cpp

Better clear the stop flag at the beginning of module_speak_sync,
otherwise if several stops are requested, the duplicate stop would be
taken by the next synth.

kali: Avoid confusion about stopping

---

README.md

See https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/

Fix htmlpreview doc links in readme

---

src/modules/module_utils.c

Festival, notably, produces initial small noise that cannot be eaten by
a 0.1% level.

module_strip_silence: Lower level to 1%

---

src/modules/Makefile.am

runpath is not transitive, libibmeci.so would then not find libetidev.
We thus have to stick to rpath, which is transitive.

ibmtts: Fix load

---

doc/speech-dispatcher.html
doc/speech-dispatcher.texi
src/modules/baratinoo.c
src/modules/espeak.c
src/modules/festival.c
src/modules/ibmtts.c
src/server/output.c
src/server/speak_queue.c

This is needed for speech-dispatcher to be able to restart at the mark.

pause: Fix pausing at __spd_ marks only

---

config/modules/epos-generic.conf
doc/speech-dispatcher.texi
src/modules/generic.c

And document the character set part of GenericLanguage
Fixes #594

generic: Fix the default encoding to be latin1

---

config/modules/baratinoo.conf
config/modules/cicero.conf
config/modules/dtk-generic.conf
config/modules/epos-generic.conf
config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/espeak-ng.conf
config/modules/espeak.conf
config/modules/festival.conf
config/modules/flite.conf
config/modules/ibmtts.conf
config/modules/ivona.conf
config/modules/kali.conf
config/modules/llia_phon-generic.conf
config/modules/mary-generic.conf
config/modules/pico.conf
config/modules/swift-generic.conf
config/modules/voxin.conf

This allows to get debugging prints from option parsing.

modules: Move Debug configuration option to beginning of file

---

src/modules/generic.c

E.g. when using various mbrola languages, we want to be able to specify
a precise voice name. Setting the voice language/type after the voice
name would override that choice.

generic: Set voice name after setting voice language and type

---

src/modules/Makefile.am

It seems automake doesn't actually run install-exec-hook after install

espeak-ng-mbrola: Make sure modulebindir exists

---

NEWS
config/speechd.conf

Now that we properly detect the list of actually working modules, and sorted
by quality, we can just automatically default to the first (thus best)
available module.

Do not set the espeak-ng module by default

---

src/modules/cicero.c
src/modules/dummy.c
src/modules/generic.c
src/modules/module_main.h
src/modules/skeleton0.c
src/modules/skeleton0_espeak-ng-async-server.c
src/modules/skeleton0_espeak-ng-async.c
src/modules/skeleton_config.c

This is needeed to keep API compatibility with previous C++ modules,
which would define a function without the const qualifier, thus not
matching the C prototype, and thus getting mangled, and thus the
module_speak weak ref would fail.

Revert module_espeak to taking a const pointer

---

src/api/python/speechd_config/config.py

- spd-conf: Do not copy config permission attributes
- spd-conf: Respect XDG basedir spec for autostart

spd-conf: Improve config copying

---

src/server/output.c
src/server/parse.c

E.g. 'spd-say -L' should be listing the voices of the default module
selected by speech-dispatcher.

Fix listing voices of default module

---

Makefile.am
build.sh
po/speech-dispatcher.pot

Removing po/speech-dispatcher.pot means that further on it'll try to
recreate it but source code is supposed to be non-writable.

Fix make distcheck

---

configure.ac

Update the module-bindir help text in configure.ac to reflect that the
default module-bindir location is now in {libexecdir} rather than
{libdir} (from commit 7e2b8409f948d5f9d3f0c1e8e859052b6c3f3872).

Fix module-bindir help text

---

src/server/module.c

Fix GET OUTPUT MODULE returning default module name

---

config/modules/cicero.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/festival.conf
config/speechd.conf

Found via `codespell -q 3 -S *.po`

FIx typos in `config/`

---

src/modules/pico.c

I noticed a while ago selecting a voice with spd-say -y when using pico didn't work unless you also specified a language with -l argument.
Today I figured out why. sd_pico first parses the voice name, then parses the language, but parsing the language changes the voice...
Doing those in reverse fixes voice selection to override language selection (which is locale based if none is given to spd-say, etc.)
With this change
spd-say -y virginie "Hello"
uses the virginie voice even though my locale is en-US.

Fix pico voice selection

---

src/api/c/libspeechd.c

Wcrtomb doesn't write a null byte after processing the character, but the
buffer is later assumed to be terminated.

spd_wchar: Initialize buffer before using

---

src/common/spd_audio.c
src/modules/module_config.c

there's no platform(s) where ltdl is necessary anymore that anyone would want to build and use speechd on, and this fixes building speechd w/ slibtool. #611 
however I don't know how to properly test the module loading to make sure it's correct so please don't merge before it's verified to actually work... :-)

drop ltdl dependency in favor of native dlopen(3) interfaces

---

src/modules/espeak.c

Dropping SSML mode loses quite a few functionalities, while we can just
tell espeak-ng the voice parameter on each synth, which is not that
costly.

espeak-ng-mbrola: keep ssml mode but set voice parameter on each synth

---

speech-dispatcherd.service.in

When speech-dispatcher is started as a service, we do not want to see it
shut down automatically.

Avoid speech-dispatcher service shutting down

---

src/server/module.c

b4a862c75460 ("Fix GET OUTPUT MODULE returning default module name") was actually overriding the default module configuration.

Fix DefaultModule configuration

---

Makefile.am
configure.ac
src/server/speechd.c

This is a follow up to merge request #763.
If Libsystemd were not available to the system, the previous implementation would nonetheless install both the socket and the dispatcher.service, which, although not a bug, wouldn't be used.
I'm also renaming HAVE_SYSTEMD to USE_SYSTEMDLIB because 
1. that's the module being checked
2. even if available, the user could choose not to use it by passing `--without-systemduserunitdir`.

Only install user units if libsystemd is available

---

src/api/c/libspeechd.c

during spd_execute_command_with_reply

libspeechd: Avoid crashing if the connection got broken

---

src/audio/alsa.c
src/audio/libao.c
src/audio/nas.c
src/audio/oss.c
src/audio/pulse.c
src/common/spd_audio.c

dlopen needs the full name so include .so extension
Set SPD_AUDIO_PLUGIN_ENTRY to correct name (ltdl adds a prefix, dlopen just uses standard name)

Fix audio plugin loading with dlopen #782

---

locale/.gitignore
locale/Makefile.am
locale/README.md
locale/symbolsrc/.gitignore

* Provide a more direct link to last CLDR release and update instructions
* Create the locale/symbolsrc directory and put a .gitignore into it

Update updating symbols instructions

---

configure.ac
src/api/c/Makefile.am
src/api/guile/gssip.c
src/audio/pulse.c
src/clients/spdsend/spdsend.h
src/modules/Makefile.am
src/server/Makefile.am

We already set _GNU_SOURCE in various places but not consistently. Let's just use autoconf's AC_USE_SYSTEM_EXTENSIONS to ensure it's always set.
Fixes failure when building tests for 0.11.4:
```
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../..  -I../../include -I../../src/api/c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include    -O2 -pipe -march=native -fdiagnostics-color=always -frecord-gcc-switches -Wreturn-type     -ggdb3 -Werror=format-security -Werror=implicit-function-declaration -Wimplicit-int -Wformat -c -o run_test.o run_test.c
run_test.c: In function ‘wait_for’:
run_test.c:93:21: error: implicit declaration of function ‘strcasestr’; did you mean ‘strcasecmp’? [-Werror=implicit-function-declaration]
93 |         while (0 == strcasestr(reply, event)) {
| …
```

Use AC_USE_SYSTEM_EXTENSIONS

---

src/common/speak_queue.c

Issue is the way stable an unstable are handled in glib.  Unstable versions are not considered as 2.67, but as 2.68.
g_memdup2 was not available in all of the 2.67.y releases.
Reported at https://forum.libreelec.tv/thread/26241-problem-building-package-on-libreelec-10/
Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>

Fix G_ENCODE_VERSION for unstable 2.67 versions

---

config/modules/espeak-ng-mbrola.conf
config/modules/espeak-ng.conf
config/modules/espeak.conf

this fixes #793
ref for buffer size: https://github.com/nvaccess/nvda/blob/a6fb2392083b5fa1bae926102135ad452746ad3c/source/synthDrivers/_espeak.py#L338

espeak: set buffer size to 300

---

src/api/python/speechd/client.py

This is something that was lost back in 2003 in commit c71d08a1de6888f8be6a007303d18bd8bcce8c65.
This is merely a missing validation, but the code looks very strange as it was, trying to perform the validation but having it not actually do anything.
---
Disclaimer: I didn't actually test this very much, and possibly the extra validation would show bugs elsewhere.  However, I do think something should be fixed in this area: either have fully working code, or remove the pieces that pretend to check yet are no-ops.

python: Fix checking all lines of a message have the same code

---

Makefile.am
configure.ac

Allow the user to disable documentation through `--disable-doc` to avoid the following build failure without makeinfo:
```
make[3]: Entering directory '/home/buildroot/autobuild/instance-2/output-1/build/speechd-0.11.4/doc'
MAKEINFO ssip.info
MAKEINFO spd-say.info
/home/buildroot/autobuild/instance-2/output-1/build/speechd-0.11.4/missing: line 81: makeinfo: command not found /home/buildroot/autobuild/instance-2/output-1/build/speechd-0.11.4/missing: line 81: makeinfo: command not found WARNING: 'makeinfo' is missing on your system.
You should only need it if you modified a '.texi' file, or
any other file indirectly affecting the aspect of the manual.
You might want to install the Texinfo package:
<https://www.gnu.org/software/texinfo/>
The spurious makeinfo call might also be the …
```

add --disable-doc

---

src/server/output.c

In the case of a pause request during some audio without any index, we still need to inject an end event, and we'll notice the pause there
Fixes #813

Add missing end event in audio queue

---

locale/README.md

* Change the name of the link to click to download the CLDR zip file
* Remove markdown for links which are not displayed as expected

Update documentation for symbols importation

---

src/api/c/libspeechd.c

fclose already closes the underlying file descriptor.

Drop duplicate socket close

---

src/api/c/libspeechd.c
src/api/c/libspeechd.h

In ec25ad9, buffering was switched from line buffering to character buffering.  This caused slow performance when large amounts of data are transferred. Instead, make each connection maintain a buffer of size SPD_REPLY_BUF_SIZE.
For me, this improves the performance of `spd-say -L > /dev/null` from 0.5s to 0.35s.
This might also fix #750, or perhaps we will also need to fix the server side as well.
Fixes #833

client library: fix buffering

---

src/server/output.c
src/server/parse.c

The protocol cannot emit it verbatim, so we have to translate.

Fix parsing and emitting space character

---

locale/symbolsrc/.gitignore

CLDR and NVDA beta are zip files and can be ignored by git.

Add *.zip to local/symbolsrc/.gitignore

---

configure.ac
src/modules/Makefile.am

Darwin apparently does not allow undefined symbols by default, so we have to explicitly tell which symbols are to be. As suggested by Mohamed Akram.

Allow _module_speak _module_speak_sync being undefined

---

src/api/c/libspeechd.c
src/modules/festival.c
src/modules/ibmtts.c
src/server/history.c
src/server/index_marking.c
src/server/output.c
src/server/parse.c
src/server/symbols.c

g_string_free conveniently returns the C pointer, and newer versions actually warn if we don't do pick it up.

Simplify g_string_free(foo, FALSE) calls

---

src/modules/module_utils.c

Strictly speaking, this could be also some character of an 8-bit encoding, but that's not very much a problem to spuriously reduce the maximum chunk by a few bytes for some characters. Less a problem than asking the caller to specify whether it's UTF-8.
Fixes #806

module_get_message_part: Avoid splitting UTF-8 sequences

---

config/modules/openjtalk.conf
configure.ac
src/modules/Makefile.am
src/modules/open_jtalk.c
src/modules/openjtalk.c

Hello,
This pull request introduces a new module named "openjtalk", using [Open JTalk](https://open-jtalk.sourceforge.net/) for high-quality Japanese text-to-speech synthesis.
To utilize this module, the `open_jtalk` executable, a dictionary, and voice data are required. On Ubuntu, these dependencies can be installed with the following command:
```bash
apt install open-jtalk open-jtalk-mecab-naist-jdic hts-voice-nitech-jp-atr503-m001
```

Add Open JTalk module

---

src/modules/module_utils.c

By design there won't be any such plugin, and the resulting warning is confusing for users looking at the log.

audio: Avoid trying to load plugin for "server" audio output

---

src/server/parse.c
src/server/speechd.c

In case the user configuration breaks all modules, we will fallback to espeak-ng without configuration, and at really worse, on dummy.

Also load espeak-ng-fallback and dummy on autodetection

---

src/audio/alsa.c
src/audio/libao.c
src/audio/oss.c
src/audio/pulse.c
src/modules/module_utils.c
src/server/speechd.c

ctime is *not* thread-safe, so we could end up with assertion failure on the ctime being empty.

Replace ctime with ctime_r

---

include/spd_audio_plugin.h
src/audio/pulse.c

With the full async interface we can control the draining: we let the server buffer fill, and when draining ask the server about the playback progression. The 20ms overlap should be enough to avoid move overruns.

pulse: Add feed_sync/_overlap support

---

po/hu.po

Hi Anybody,
With near the RC3 release, I updated the po/hu.po hungarian translation file. :-):-)
Only one new message are untranslated previous, but this is done now.
If this is possible, if have a little time please merge this PR into the master branch.
I have got a small question with punctuation dictionary localization related:
In Orca 46.0 version Speech-dispatcher the Espeak-ng module says the „ (u+201e character) with double low quote, and says the u+201d character with double right quote english language text.
Previous, this simbols are right localized In Orca source code the 44.2 version the Orca po/hu.po file, but Orca developers removed or changed I think this simbol handling after the 46.0 version (or before the 46.0 version publication), and this simbols translations perhaps …

po/hu.po: updated hungarian translation

---

src/server/speechd.c

This will make it easier to tune the startup and reload, notably on MacOS.
Almost no behavior change here: we just now always load modules even when not finding the configuration file.
Suggested-by: Mohamed Akram <mohd.akram@outlook.com>

Split out loading configuration, loading modules, and checking them

---

src/modules/generic.c

module_strip_ssml removes some text, so before passing it to g_convert_with_fallback we need to update the number of bytes.
Fixes #927

generic: Fix message length after stripping ssml

---

src/modules/generic.c

6c16359961f4 ("generic: rework message processing") compared charset to utf-8 erroneously.

generic: Fix message recoding

---

src/api/c/libspeechd.c

In case e.g. speech dispatcher crashes, we have to make get_line error out, so the client can notice it and reattempt opening speech dispatcher.

libspeechd: catch end of file

---

src/server/output.c

The audio thread may call speak_queue_stop_or_pause after speaking_module is cleared by is_sb_speaking.

spd: Fix crash on cancelling with server audio

---

src/audio/nas.c

AuUint32 is long unsigned there.

Fix compiler warning on 32bit arch

---

src/server/output.c

fflush(NULL) would wait for all output emissions, and thus wait for unrelated modules.

Avoid spurious synchronization

---

src/server/module.c
src/server/module.h
src/server/output.c

Otherwise:
- we could be mixing up messages and replies across modules
- for instance when a generic module is playing a message, and we are asked to quit, we would be uselessly waiting for the play to end on the generic module while trying to close another module
It does make a lot sense anyway.

Separate out output management for different output modules

---

src/audio/alsa.c
src/audio/libao.c
src/audio/nas.c
src/audio/oss.c
src/audio/pulse.c

in modules stderr is fine but in the server we should really be calling MSG which emits in the log. module_utils already does provide a MSG function that emits to stderr for the module-side audio case, actually.

audio: Fix logging from audio modules in server-side audio

---

src/server/server.c

SSML doesn't make sense for those commands, and it can break processing of them.
For example, if a symbol expansion leads to converting it to a TEXT command, it then has to be valid SSML (including surrounding <speak> tags), otherwise a module might not accept it.  If the client is not in SSML mode it worked fine as the input was translated to SSML, but if the client was in that mode the input was still assumed to already be SSML, although it actually wasn't as it's not possible (nor makes sense) to send SSML through CHAR and KEY.
This e.g. broke the Baratinoo module for such symbol expansions (e.g. when "y" is getting translated to "igrèque" to workaround pronunciation issues in some synthesizers).

Ignore client SSML mode for CHAR and KEY commands

---

src/server/speechd.c

It was missing from the module order list, leading to have it at the very bottom of the list.  Sort it higher so it can be selected by default in more situations.
Sorting position is somewhat arbitrary, I merely listened to samples for Pico, RHVoice and IVONA and deemed Baratinoo better.  I didn't check all other voices because I didn't easily find relevant samples to listen to, but it's unlikely a user has several of these engines that usually either need specific setup or require buying the corresponding non-free software.

Sort Baratinoo engine higher

---

src/modules/espeak.c

espeak_ng_GetSampleRate does not report the rate of mbrola voices.
Fixes #949

espeak-ng-mbrola: Fix mbrola voices with rate different from 22KHz

---

config/modules/espeak-ng-mbrola-generic.conf

espeak-ng-mbrola-generic.conf: Avoid missing argument to option 'GenericPunctNone'

---

src/clients/say/say.c
src/modules/espeak.c

Fixes build failures on Solaris with gcc 14 since the legacy index() function is only defined in the legacy strings.h header, but these files only include the standard string.h header which defines the standard strchr() function.
```
../../../src/modules/espeak.c: In function ‘espeak_list_synthesis_voices’:
../../../src/modules/espeak.c:909:40: error: implicit declaration of function ‘index’ [-Wimplicit-function-declaration]
909 |                                 dash = index(voicename, '-');
|                                        ^~~~~
../../../src/modules/espeak.c:909:40: warning: incompatible implicit declaration of built-in function ‘index’ [-Wbuiltin-declaration-mismatch]
```

Use strchr() instead of deprecated index()

---

.gitignore
README.md
configure.ac
run-spd-say.in
run-speechd.in

That allows to run the just-built speech-dispatcher and call spd-say on it without having to interfere with an existing installation.

Add a run-spd-say script and make run-speechd and run-spd-say able to talk directly

---

src/api/python/speechd/client.py

Calling sys.exit from a thread other than the main one has no effect, because
sys.exit() only raises the SystemExit exceptions, which is ignored in
non-main threads.
Using a simple return statement is sufficient, and it also allows to
remove an import.

Do not call sys.exit in a thread

---

src/audio/pulse.c

This reverts commit 2ea44ed0c44c4e5ed8987c0c50559cab1fe2c9ee.
Michael Gorse reported some regressions, see
https://mail.gnu.org/archive/html/speechd-discuss/2024-07/msg00000.html

Revert "pulse: Set prebuf to min_audio_length instead of tlength"

---

src/server/output.c

The `speak` thread can change the `speeking_module` to NULL while we are in this function.  So even though `speeking_module` is tested for NULL, this is not good enough in a multi-threading environment.
This change grabs a local copy of `speeking_module` and then tests that for NULL so that even if a thread context switch were to occur and `speeking_module` is set to NULL, the local copy will remain stable and usable.

Issue #971 Make local copy of speeking_module to ensure it can be tested for NULL

---

src/modules/module_utils.h
src/server/speechd.h

speechd.h:63: error: redefinition of 'union semun'

Fix compilation on OpenBSD.

---

src/server/speechd.c

[Multispeech](https://github.com/poretsky/multispeech) is a Speech Dispatcher compatible, open source, multilingual speech synthesis system. It can be built yourself, and is also distributed as a [ready-made package](https://poretsky.github.io/packages/) for various distributions, including through the [Debian repository](https://packages.debian.org/search?keywords=multispeech).
Multispeech utilizes third party speech synthesis software to perform actual TTS transformation. Being capable to detect language by text nature it can automatically choose an appropriate TTS for each one. For the moment English, German, French, Italian, Spanish, Portuguese and Russian languages are supported.
Multispeech uses eSpeak and MBROLA technologies, as well as an improved linguistic backend for English …

Add Multispeech to prioritization order of modules

---

config/modules/mimic3-generic.conf

Minor fix to comments accidentally saved from another module taken as a basis.

Fix comments in mimic3-generic output module

---

configure.ac

AC_HELP_STRING has been deprecated for a long time and triggers a warning:
configure.ac:187: warning: The macro 'AC_HELP_STRING' is obsolete.
https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Obsolete-Macros.html#Obsolete-Macros
Let’s switch to the modern AS_ variant, we already use it elsewhere in the file.

configure: Use AS_HELP_STRING

---

configure.ac

configure.ac:71: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
./lib/autoconf/specific.m4:541: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:71: the top level
configure.ac:71: warning: AC_LINK_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
./lib/autoconf/specific.m4:541: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:71: the top level
configure.ac:71: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
./lib/autoconf/specific.m4:541: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:71: the top level
configure.ac:71: warning: AC_CHECK_INCLUDES_DEFAULT was called before AC_USE_SYSTEM_EXTENSIONS
./lib/autoconf/specific.m4:541: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:71: the top level

configure: Fix AC_USE_SYSTEM_EXTENSIONS warning

---

po/LINGUAS

Hello,
Georgian translation is present even in 0.11.5, but it's not enabled in LINGUAS file and as a result, is not being installed/used.
Enabling it.
Temuri

Update LINGUAS: Enable Georgian

---

src/api/c/libspeechd.c

The protocol cannot take a space character.

Fix spd-say -k ' '

---

src/modules/espeak.c

So that espeak picks up its own pronunciation in all languages.

espeak-ng: Convert unspeakable keys to speakable form

---

src/modules/generic.c

data is freed by the caller, so we have to duplicate it.

generic: Fix random garbage on non-text utterances

---

.github/workflows/ci.yml
config/modules/Makefile.am
config/modules/cxxpiper.conf
configure.ac
src/modules/.gitignore
src/modules/Makefile.am
src/modules/cxxpiper.cpp

'Native' means it's written in C++, so it does not incur the overhead of the generic output modulebased on the piper command line utility.

A native output module based on piper TTS.

---

src/modules/generic.c

dd759d73f19a ("generic: Fix random garbage on non-text utterances") broke the generic module.

generic: Fix crash

---

config/modules/dtk-generic.conf
config/modules/epos-generic.conf
config/modules/espeak-mbrola-generic.conf
config/modules/espeak-ng-mbrola-generic.conf
config/modules/llia_phon-generic.conf
config/modules/mary-generic.conf
config/modules/mimic3-generic.conf
config/modules/swift-generic.conf
doc/speech-dispatcher.html
doc/speech-dispatcher.texi
src/modules/generic.c

This avoids having to use GenericLanguage just to specify the charset, and keep it only for the original purpose: translate from iso code to synth-specific code.

generic: Add GenericDefaultCharset parameter

---

src/server/output.c

Otherwise this can get stuck when leaving the Orca preference dialog:
6  ___pthread_cond_wait (cond=0x55e35e11fcd0, mutex=0x55e35e11fca8) at ./nptl/pthread_cond_wait.c:458 7  0x000055e340c5a58b in output_read_reply (output=0x55e35e11fc40) at output.c:299 8  0x000055e340c5adae in output_get_voices (output=0x55e35e11fc40, language=0x0, variant=0x0) at output.c:521 9  0x000055e340c5b1dc in output_list_voices (module_name=0x55e35e11cb00 "espeak-ng", language=0x0, variant=0x0) at output.c:601 10 0x000055e340c5228d in parse_list (buf=0x55e35e12bc10 "LIST SYNTHESIS_VOICES\r\n", bytes=23, fd=34, speechd_socket=0x55e35e12cb20) at parse.c:964 11 0x000055e340c4d97f in parse (buf=0x55e35e12bc10 "LIST SYNTHESIS_VOICES\r\n", bytes=23, fd=34) at parse.c:108 12 0x000055e340c478f1 in serve (fd=34) at …

output: Add missing signaling when not reading message any more

---

src/server/module.h
src/server/output.c

After joining the output_thread, we would not consume the event, and thus stay stuck inside output_read_reply while running the next command.

output: cope with spurious event from output module

---

src/modules/cicero.c
src/modules/dummy.c
src/modules/generic.c

It was never documented as returning the number of bytes. If that happens to be zero, it would wrongly believed to be failing.

Fix value returned by module_speak

---

config/speechd.conf

This is the file that gets installed and it is a bit weird when editing
one's configuration file to land on a blank line when opening it.

Remove blank line at THE begiNning of config/speechd.conf

---

src/modules/module_main.c

This reverts commit 3e5c5b7a8da66f79cd7d7f6e4cb631ec2abd1b8d.
We are not actually supposed to call module_report_event_begin/end inside module_speak... Better make the module hang (which is easy to see in gdb) rather than the server hang (which requires understanding that begin/end can only happen after the 200 ack).

Revert "module_main: make module_stdout_mutex recursive"
